# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ADMN\Documents\Porject\python\Qt5\bike-distribution-model\core\window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1005, 592)
        MainWindow.setMinimumSize(QtCore.QSize(1005, 592))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_cell = QtWidgets.QVBoxLayout()
        self.verticalLayout_cell.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_cell.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_cell.setSpacing(0)
        self.verticalLayout_cell.setObjectName("verticalLayout_cell")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_cell.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout_cell)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_1.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(321, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_start.setEnabled(True)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_start.setMaximumSize(QtCore.QSize(224, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_pause = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_pause.setEnabled(True)
        self.pushButton_pause.setGeometry(QtCore.QRect(100, 50, 75, 23))
        self.pushButton_pause.setMaximumSize(QtCore.QSize(224, 23))
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.pushButton_stop = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_stop.setEnabled(True)
        self.pushButton_stop.setGeometry(QtCore.QRect(190, 50, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        self.pushButton_stop.setMaximumSize(QtCore.QSize(224, 23))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_1.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "那啥模型"))
        self.groupBox_5.setTitle(_translate("MainWindow", "显示区"))
        self.groupBox_4.setTitle(_translate("MainWindow", "参数设置"))
        self.groupBox.setTitle(_translate("MainWindow", "控制区"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_pause.setText(_translate("MainWindow", "停止"))
        self.pushButton_stop.setText(_translate("MainWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

